task_id:"Yit6RD3NnunNJ2rM00s3E" situation_id:"GIaoJQ0EJNdx88QHnepHv" check_item:{check_item_id:"gBrCOhjLzns0A8LWSZJX0" command:{command_id:"pMv5KBynTNH0lCSV393fk" command_line:"progate diagnose"}} check_item:{check_item_id:"I4bny4agHfR5tPGnR3AaT" command:{command_id:"TL6PMUkpLNHEeiVL6ansX" command_line:"npx tsc --noEmit ./src/quiz/primitives.ts"}}